# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b78f432164225cefabba4027963a8438966a7aa39564d1d7e6f14b45b8dca06c896473fe2400b0065ca210e52c7c92c7248c67e4c5b89204481ca33b248af4d

test:
  secret_key_base: 69dedcaa4e58d8ab2954a702dad70052e35745100b5ee1c61b546b84fbfc13377733f05a7d40583c29f5f07098454528d39ba6a3b178dbdffadae50f8ce3246d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
